### ISSUE TITLE
Blocks not working

### ISSUE THREAD

**Issue by peterdcasey** [Cadiboo/Example-Mod#13]
I know this is too general a question but using IntelliJ and your example mod code for some reason the block example is not working for me. If there is something simple you have heard about this issue. The items work fine.

Sorry about how non-specific this is.

Thank you, Peter

**Comment by Cadiboo** [comment]
Can you define "not working"?

**Comment by peterdcasey** [comment]
Very sorry about how vague this is. Your mod does everything but the example block does not show up in the inventory. The ore and the item work fine. I am a total noob.

Please do not spend much time on this, I just wondered if you had heard something about the block.

Thank you, Peter

+----------------------------------------+
| Peter Casey                            |
| Professor of CIS                       |
| Central Oregon Cmty. College           |
| Bend OR 97701                          |
| 541-383-7723                           |
| Pioneer 214                            |
| https://www.cocc.edu/employees/pcasey/ |
+----------------------------------------+

**Comment by Cadiboo** [comment]
What does “does not show up” mean? Does it not exist (doesn’t appear in any creative tab)? Does it not display (invisible but you can hover over it)? Does it have a missing texture?

**Comment by Cadiboo** [comment]
Closed as 1.12.2 is old and no-longer supported by Forge.
