### ISSUE TITLE
Blocks do not appear in Creative Tab

### ISSUE THREAD

**Issue by willihay** [Cadiboo/Example-Mod#14]
Love this example mod. Nice design. I've just refactored my mod to incorporate some of your ideas. However, using your registration code in my mod, I noticed that none of the blocks I'm registering appear in my mod's custom creative tab. I finally figured out why. You're setting the creative tab on the block's ItemBlock (when you register the ItemBlock) when really I think you need to be setting it for the Block - inside the Block's constructor, for example. This is corroborated by the fact that if you call getCreativeTab for any ItemBlock, it goes and gets it from the Block.

**Comment by AqourSoro** [comment]
Agreed, nice design, however, same problem when registering blocks.

**Comment by Cadiboo** [comment]
Closed as 1.12.2 is old and no-longer supported by Forge.
