### ISSUE TITLE
Class must be either be declared abstract or implement abstract method

### ISSUE THREAD

**Issue by rushiiMachine** [Cadiboo/Example-Mod#15]
Was having trouble not using `IHasModel`, got linked to your example mod. When using the `ModCreativeTabs` i get an error from intelliJ like this: 

> Class 'Anonymous class derived from CustomCreativeTab' must either be declared abstract or implement abstract method 'getTabIconItem()' in 'CreativeTabs'

Here:
```
public static final CustomCreativeTab CREATIVE_TAB = new CustomCreativeTab(MOD_ID, true) {
    @Override
    public ItemStack createIcon() {
        return TAB_ICON_ITEMSTACK;
    }
};
```

Also get an error further down the code like this:
> Method does not override method from its superclass

Here:
```
@SideOnly(Side.CLIENT)
@Override
abstract public ItemStack createIcon();
```
Link to my class: [Github](https://github.com/DiamondMiner88/Character-Mod/tree/master)

**Comment by Cadiboo** [comment]
Solved by updating MCP mappings. Relevant forums post http://www.minecraftforge.net/forum/topic/69832-trouble-with-cadiboos-example-mod/
