### ISSUE TITLE
Populating Ores

### ISSUE THREAD

**Issue by elizabethlfransen** [Cadiboo/Example-Mod#16]
Would you be able to add an example of populating the world with example_ore?

**Comment by kwpugh** [comment]
I originally used the example mod to create my Easy Steel mod.   I had to scrape around the web to figure out the ore gen part in 1.14.4.

My source code for ore gen is pretty straightforward.

https://github.com/kwpugh/easy_steel/tree/1.14/src/main/java/com/kwpugh/easy_steel

There are three parts:
- the ore generator class in the world package
- the mod config class (to enable/disable ore) in the util package
- add a call for the ore generator class from setup in the main class (easysteel.java)

Hope that helps you.

Regards

**Comment by elizabethlfransen** [comment]
Thank you, your source code is very helpful!
