### ISSUE TITLE
Generating structures

### ISSUE THREAD

**Issue by filips123** [Cadiboo/Example-Mod#22]
Can you also make tutorial(s) and example mod code for generating custom structures? I think that there aren't many tutorials and examples of structure-generating mods (at least for latest Minecraft/Forge versions), so this would be quite nice addition.

Things that I would like to see in such tutorial:

* Configuration:
  * How common/rare is the structure: Maybe simply how common per certain number of chunks it is, some different or more advanced configuration...
  * Where it spawns: Dimensions and biomes, locations (surface, underground, sky...,), height, near or far from other (both specific and any) structures, depending on terrain (for example at top/bottom/edge of mountain, more plains-like terrain...), some more randomness...

* Locating structure with `/locate` command. If the structure is bigger also where exactly should `/locate` point to.

* Generation:
  * Directly in code.
  * Using structure blocks.
  * Combinations of both things. For example, modifying structure block-based structure to give it some more randomness, depending on biome or terrain, merging it with terrain, making part of structure using structure blocks and part using code...

* Bigger structures:
  * Connecting parts of structures to make bigger structure.
  * Directly in code.
  * Using jigsaw block.
  * Again combination of both things. For example, generally using jigsaw block to randomly select next structure part while manually always selecting specific part when and/or until certain condition is meet (height, biome...) and then process normally using jigsaw blocks. Some more specific example: First specific part ("entrance") is randomly chosen, which then uses jigsaw block to randomly chose new part next to entrance, then starts choosing that same part again until some condition is meet (for example height), then again using jigsaw block to create new part and then normally processing generation using jigsaw blocks.

I know this is quite a lot of things, but at least some could be added for start, and other could be added later.

**Update:** I found [TelepathicGrunt/StructureTutorialMod](https://github.com/TelepathicGrunt/StructureTutorialMod) which seems pretty good example mod. Then, you don't really need to create whole new mod for structures, but you could include some things in tutorial, link that existing mod and/or contribute some features that aren't ready yet (like jigsaw block, more advanced generation, spawning configuration...).

**Comment by Cadiboo** [comment]
Hey, I try not teach people about stuff I don't fully understand and I know literally nothing about structures or world gen at all. I've always tried to steer clear of it because of the maths it involves. However, it got rewritten in 1.16 so this might be the time for me to learn :). Thanks for putting so much effort into this issue, I'm sorry nothing came of it. I'll definitely link TelepathicGrunt's repo in my tutorials though.
