### ISSUE TITLE
Remove method and use EntityEntryBuilder directly

### ISSUE THREAD

**Issue by Cadiboo** [Cadiboo/Example-Mod#5]
https://github.com/Cadiboo/Example-Mod/blob/6a1ba1042d63b80fb6e6676a0d04018e0bc1f3ae/src/main/java/cadiboo/examplemod/EventSubscriber.java#L92-L104

**Comment by JamesYeoman** [comment]
One minor change you should probably do as well: remove the assignments from each stage of the builder. The point of the instance returns of a builder is so that you can chain-call. And besides, if you're not chain-calling, you still don't need to re-assign builder

**Comment by Cadiboo** [comment]
> One minor change you should probably do as well: remove the assignments from each stage of the builder. The point of the instance returns of a builder is so that you can chain-call. And besides, if you're not chain-calling, you still don't need to re-assign builder

I wrote this code while struggling with the auto formatter putting everything on 1 line, this was meant to be a temporary fix but I never actually fixed it
